///////////////////////////////////////////////////////////
//  Description.cs
//  Implementation of the Class Description
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:16 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modul1
{


    public class Description : IDescription
    {

        private Dataset dataset;
        private int id;
        private static int staticID;
        public List<Module1Property> propertyList;

        public Description()
        {

        }

        ~Description()
        {

        }

        /// 
        /// <param name="dataset"></param>
        public Description(Dataset dataset)
        {

        }

        /// 
        /// <param name="property"></param>
        public void AddOrReplaceProperty(IModule1Property property)
        {

        }

        private int createUniqueID()
        {

            return 0;
        }

        public Dataset Dataset
        {
            get
            {
                return dataset;
            }
            set
            {
                dataset = value;
            }
        }

        /// 
        /// <param name="code"></param>
        public bool DoesPropertyExist(SignalCode code)
        {

            return false;
        }

        /// 
        /// <param name="code"></param>
        public IModule1Property GetPropertyByCode(SignalCode code)
        {

            return null;
        }

        public int ID
        {
            get
            {
                return id;
            }
            set
            {
                id = value;
            }
        }

        public List<IModule1Property> Properties()
        {

            return null;
        }

        /// 
        /// <param name="property"></param>
        public void UpdateProperty(IModule1Property property)
        {

        }


    }//end Description

}