///////////////////////////////////////////////////////////
//  ListDescription.cs
//  Implementation of the Class ListDescription
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modul1
{





    public class ListDescription : IListDescription
    {

        public List<Description> descriptions;



        ~ListDescription()
        {

        }

        public ListDescription()
        {

        }

        /// 
        /// <param name="description"></param>
        public void AddOrReplaceDescription(IDescription description)
        {

        }

        public IDescription Descriptions()
        {

            return null;
        }

        /// 
        /// <param name="dataset"></param>
        public bool DoesDescriptionExist(Dataset dataset)
        {

            return false;
        }

        /// 
        /// <param name="datset"></param>
        public IDescription GetDescriptionByDataset(Dataset datset)
        {

            return null;
        }

        /// 
        /// <param name="dataset"></param>
        public bool IsDatasetFull(Dataset dataset)
        {

            return false;
        }

        /// 
        /// <param name="property"></param>
        public void UpdateProperty(IModule1Property property)
        {

        }

    }//end ListDescription
}