///////////////////////////////////////////////////////////
//  Module1DataAdapter.cs
//  Implementation of the Class Module1DataAdapter
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:19 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modul1
{


    public class Module1DataAdapter
    {

        private ILogging logger;

        public Module1DataAdapter()
        {

        }

        ~Module1DataAdapter()
        {

        }

        /// 
        /// <param name="logger"></param>
        public Module1DataAdapter(ILogging logger)
        {

        }

        /// 
        /// <param name="signal"></param>
        /// <param name="value"></param>
        public Module1Property PackToModule1Property(SignalCode signal, double value)
        {

            return null;
        }

    }//end Module1DataAdapter
}