///////////////////////////////////////////////////////////
//  Module1DatabaseManager.cs
//  Implementation of the Class Module1DatabaseManager
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:19 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modul1
{


    public class Module1DatabaseManager
    {

        private ILogging logger;

        public Module1DatabaseManager()
        {

        }

        ~Module1DatabaseManager()
        {

        }

        /// 
        /// <param name="logger"></param>
        public Module1DatabaseManager(ILogging logger)
        {

        }

        /// 
        /// <param name="property"></param>
        /// <param name="timestamp"></param>
        public bool WriteProperty(Module1Property property, DateTime timestamp)
        {

            return false;
        }

    }//end Module1DatabaseManager
}
