///////////////////////////////////////////////////////////
//  Module1ServiceProvider.cs
//  Implementation of the Class Module1ServiceProvider
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:19 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Modul1
{

    public class Module1ServiceProvider : IModule1
    {

        private ILogging logging;
        private IModule2Update module2Proxy;
        private Module1DataAdapter dataAdapter;
        private ListDescription listDescription;
        private Module1DatabaseManager databaseManager;

        public Module1ServiceProvider()
        {

        }

        ~Module1ServiceProvider()
        {

        }

        /// 
        /// <param name="logger">Logger</param>
        /// <param name="module2Proxy"></param>
        public Module1ServiceProvider(ILogging logger, IModule2Update module2Proxy)
        {

        }

        /// 
        /// <param name="value"></param>
        /// <param name="signalCode"></param>
        public bool UpdateDataset(double value, SignalCode signalCode)
        {

            return false;
        }


    }//end Module1ServiceProvider
}