///////////////////////////////////////////////////////////
//  ICollectionDescription.cs
//  Implementation of the Interface ICollectionDescription
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ICollectionDescription  {

	IHistoricalCollection Collection{
		get;
		set;
	}

	Dataset Dataset{
		get;
		set;
	}

	int ID{
		get;
		set;
	}
}//end ICollectionDescription