///////////////////////////////////////////////////////////
//  IDateValidation.cs
//  Implementation of the Interface IDateValidation
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IDateValidation  {

}//end IDateValidation