///////////////////////////////////////////////////////////
//  IDescription.cs
//  Implementation of the Interface IDescription
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IDescription  {

	/// 
	/// <param name="property"></param>
	void AddOrReplaceProperty(IModule1Property property);

	Dataset Dataset{
		get;
		set;
	}

	/// 
	/// <param name="code"></param>
	bool DoesPropertyExist(SignalCode code);

	/// 
	/// <param name="code"></param>
	IModule1Property GetPropertyByCode(SignalCode code);

	int ID{
		get;
		set;
	}

	List<IModule1Property> Properties
    {
        get;
        set;
    }

}//end IDescription