///////////////////////////////////////////////////////////
//  IModule1Property.cs
//  Implementation of the Interface IModule1Property
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IModule1Property  {

	SignalCode Code{
		get;
		set;
	}

	double Module1Value{
		get;
		set;
	}
}//end IModule1Property