///////////////////////////////////////////////////////////
//  IModule2DirectUpdate.cs
//  Implementation of the Interface IModule2DirectUpdate
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

[ServiceContract]
public interface IModule2DirectUpdate  {

    [OperationContract]
	/// 
	/// <param name="code"></param>
	/// <param name="value"></param>
	void WriteToHistory(SignalCode code, double value);

    [OperationContract]
    bool Ping();
}//end IModule2DirectUpdate