///////////////////////////////////////////////////////////
//  IModule2History.cs
//  Implementation of the Interface IModule2History
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IModule2History  {

	/// 
	/// <param name="startDate"></param>
	/// <param name="endDate"></param>
	IModule2Property ReadHistory(DateTime startDate, DateTime endDate);
}//end IModule2History