///////////////////////////////////////////////////////////
//  IModule2Property.cs
//  Implementation of the Interface IModule2Property
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IModule2Property  {

	SignalCode Code{
		get;
		set;
	}

	double Value{
		get;
		set;
	}
}//end IModule2Property