///////////////////////////////////////////////////////////
//  IModule2History.cs
//  Implementation of the Interface IModule2History
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

[ServiceContract]
public interface IModule2History  {


    [OperationContract]
	/// 
	/// <param name="startDate"></param>
	/// <param name="endDate"></param>
	List<IModule2Property> ReadHistory(DateTime startDate, DateTime endDate);

    [OperationContract]
    bool Ping();
}//end IModule2History