///////////////////////////////////////////////////////////
//  IModule2Update.cs
//  Implementation of the Interface IModule2Update
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface IModule2Update  {

	/// 
	/// <param name="property"></param>
	bool UpdateDatabase(IListDescription property);
}//end IModule2Update