///////////////////////////////////////////////////////////
//  SignalCode.cs
//  Implementation of the Enumeration SignalCode
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:21 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public enum SignalCode : int {

	CODE_ANALOG,
	CODE_DIGITAL,
	CODE_CUSTOM,
	CODE_LIMITSET,
	CODE_SIGNLENODE,
	CODE_MULTIPLENODE,
	CODE_CONSUMER,
	CODE_SOURCE

}//end SignalCode