///////////////////////////////////////////////////////////
//  Module1DatabaseManager.cs
//  Implementation of the Class Module1DatabaseManager
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:19 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SQLite;

namespace Modul1
{


    public class Module1DatabaseManager
    {

        private ILogging logger;
        private SQLiteConnection databaseConnection;

        /// 
        /// <param name="logger">Logger</param>
        public Module1DatabaseManager(ILogging logger, string databasePath)
        {
            this.logger = logger;
            databaseConnection = new SQLiteConnection();
            databaseConnection.Open();
        }

        /// 
        /// <param name="property">Module 1 property</param>
        public void WriteProperty(IModule1Property property)
        {

            logger.LogNewInfo(string.Format("Trying to write property with signal code {0} and value {1} to database", property.Code, property.Module1Value));
        }

    }//end Module1DatabaseManager
}
