///////////////////////////////////////////////////////////
//  Module1DataAdapter.cs
//  Implementation of the Class Module1DataAdapter
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:19 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common;

namespace Modul1
{


    public class Module1DataAdapter : IModule1DataAdapting
    {

        private ILogging logger;

        public Module1DataAdapter(ILogging logger)
        {
            this.logger = logger;
        }


        /// 
        /// <param name="signal">Signal code</param>
        /// <param name="value">Signal value</param>
        public IModule1Property PackToModule1Property(SignalCode signal, double value)
        {
            logger.LogNewInfo(string.Format("Packing signal {0} and value {1} to module 1 property", signal.ToString(), value));
            return new Module1Property(signal, value);
        }

    }//end Module1DataAdapter
}