///////////////////////////////////////////////////////////
//  HistoricalCollection.cs
//  Implementation of the Class HistoricalCollection
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:17 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HistoricalCollection : IHistoricalCollection {

	public List<Module2Property> properties;



	~HistoricalCollection(){

	}

	public HistoricalCollection(){

	}

	public List<IModule2Property> Properties{

		return null;
	}

}//end HistoricalCollection