///////////////////////////////////////////////////////////
//  LogMessage.cs
//  Implementation of the Class LogMessage
//  Generated by Enterprise Architect
//  Created on:      19-May-2020 3:44:02 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace LoggerSpace
{
    public class LogMessage {

	    private string message;

	    public LogMessage(string message){
            this.message = message;
	    }

	    ~LogMessage(){

	    }

	    public string GetInfoMessage(){

            return string.Format("[INFO] [{0}] {1}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), message);
	    }

	    public string GetWarningMessage(){

            return string.Format("[WARNING] [{0}] {1}", DateTime.Now.ToString("dd-MM-yyyy HH:mm:ss"), message);
        }

    }//end LogMessage
}


