///////////////////////////////////////////////////////////
//  LogWriter.cs
//  Implementation of the Class LogWriter
//  Generated by Enterprise Architect
//  Created on:      19-May-2020 3:44:03 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class LogWriter {

	private string filename;

	~LogWriter(){

	}

	public LogWriter(){

	}

	/// 
	/// <param name="filename"></param>
	public LogWriter(string filename){
        this.filename = filename;
	}

	/// 
	/// <param name="message"></param>
	public void WriteToFile(string message){
        using (StreamWriter writer = File.AppendText(filename))
        {
            writer.WriteLine(message);
        }
    }

}//end LogWriter