///////////////////////////////////////////////////////////
//  Input.cs
//  Implementation of the Class Input
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace Input
{
    public class Input
    {

        private IModule2History historyWritingProxy;
        private ILogging logger;
        private IModule1 module1Proxy;

        public Input()
        {
            
        }

        ~Input()
        {

        }

        /// 
        /// <param name="logger"></param>
        /// <param name="historyProxy"></param>
        /// <param name="module1Proxy"></param>
        public Input(ILogging logger, IModule2History historyProxy, IModule1 module1Proxy)
        {

        }

        public void ActivateWriting()
        {

        }

        public void GenerateSignals()
        {

        }

        public void StartDataFlow()
        {

        }

    }//end Input
}