///////////////////////////////////////////////////////////
//  Input.cs
//  Implementation of the Class Input
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:18 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common;
using System.Threading;

namespace Input
{
    public class Input : IInput
    {

        private IModule2DirectUpdate historyWritingProxy;
        private ILogging logger;
        private IModule1 module1Proxy;

        public Input()
        {
            
        }

        ~Input()
        {

        }

        /// 
        /// <param name="logger"></param>
        /// <param name="historyProxy"></param>
        /// <param name="module1Proxy"></param>
        public Input(ILogging logger, IModule2DirectUpdate historyProxy, IModule1 module1Proxy)
        {
            this.logger = logger;
            historyWritingProxy = historyProxy;
            this.module1Proxy = module1Proxy;
        }
        
        public void GenerateSignals()
        {
            while(true)
            {
                Random rand = new Random();

                int code = rand.Next(8);
                double value = rand.NextDouble() * 1001;

                module1Proxy.UpdateDataset(value, (SignalCode)code);

                Thread.Sleep(3000);
            }
        }

        public void StartDataFlow()
        {
            Thread t = new Thread(GenerateSignals);
            t.Start();
        }

        public void sendSignal(int signal, double value)
        {
            if(value < 0 || signal < 0 || signal > 7)
            {
                throw new Exception("Given values does not match specified interval!");
            }
            else
            {
                historyWritingProxy.WriteToHistory((SignalCode)signal, value);
            }
        }
        
    }//end Input
}