///////////////////////////////////////////////////////////
//  Module2DataAdapter.cs
//  Implementation of the Class Module2DataAdapter
//  Generated by Enterprise Architect
//  Created on:      18-May-2020 4:57:20 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Common;

namespace Module2 {
    public class Module2DataAdapter {

	    private ILogging logger;

	    public Module2DataAdapter(){

	    }

	    ~Module2DataAdapter(){

	    }

	    /// 
	    /// <param name="logger">Logger for this module</param>
	    public Module2DataAdapter(ILogging logger){
            this.logger = logger;
	    }

	    /// 
	    /// <param name="signal">Signal code</param>
	    /// <param name="value">Signal value</param>
	    public Module2Property PackToModule2Property(SignalCode signal, double value){

            return new Module2Property(signal, value);
	    }

	    /// 
	    /// <param name="description">Description of dataset from module 1</param>
	    public CollectionDescription RepackToCollectionDescription(IDescription description){

            int id = description.ID;
            Dataset dataset = description.Dataset;
            List<Module2Property> properties = new List<Module2Property>();

            foreach(IModule1Property property in description.Properties())
	    }

	    /// 
	    /// <param name="listDescription">List description from module 1</param>
	    public List<CollectionDescription> RepackToCollectionDescriptionArray(IListDescription listDescription){

		    return null;
	    }

	    /// 
	    /// <param name="module1Property">Module 1 property to be repacked</param>
	    public Module2Property RepackToModule2Property(IModule1Property module1Property){

            Module2Property property = new Module2Property(module1Property.Code, module1Property.Module1Value);

            return property;
	    }

    }//end Module2DataAdapter
}


